import type { Harness } from './types';

/** Built-ins enabled on a fresh install. Others start disabled until the user turns them on. */
export const DEFAULT_ENABLED_HARNESS_IDS: ReadonlySet<string> = new Set(['universal', 'claude-code', 'codex']);

/**
 * Built-in Harness skill roots, checked against the linked vendor documentation.
 * Paths use `~` for the current macOS user's home and workspace paths are relative.
 * `reads*Agents` means the product itself documents discovery of Agent Skills' shared
 * `~/.agents/skills` / `.agents/skills` path; it is not inferred from installer support.
 * The primary paths are where apply writes: the location the vendor currently documents or its own
 * installer targets. Roots a product still loads only for backward compatibility are read roots.
 */
export const BUILTIN_HARNESSES: Harness[] = [
  {
    id: 'universal',
    name: '通用 Agents 技能',
    icon: 'globe',
    userSkillsPath: '~/.agents/skills',
    workspaceSkillsRelativePath: '.agents/skills',
    origin: 'builtin',
    kind: 'universal',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    documentationUrl: 'https://agentskills.io/specification',
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    icon: 'claude',
    userSkillsPath: '~/.claude/skills',
    workspaceSkillsRelativePath: '.claude/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: false,
    readsWorkspaceAgents: false,
    command: 'claude',
    versionArgs: ['--version'],
    documentationUrl: 'https://code.claude.com/docs/en/skills',
  },
  {
    id: 'codex',
    name: 'Codex CLI',
    icon: 'codex',
    // Codex documents the shared Agent Skills directories as its local roots.
    userSkillsPath: '~/.agents/skills',
    workspaceSkillsRelativePath: '.agents/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    // `$CODEX_HOME/skills` is marked deprecated in the loader but still loaded for backward
    // compatibility. Project `.codex/skills` is loaded from each project `.codex/` config folder,
    // though the docs do not list it.
    extraUserSkillsPaths: ['~/.codex/skills'],
    extraWorkspaceSkillsRelativePaths: ['.codex/skills'],
    command: 'codex',
    versionArgs: ['--version'],
    documentationUrl: 'https://developers.openai.com/codex/skills',
  },
  {
    id: 'codex-app',
    name: 'Codex Desktop',
    icon: 'codex',
    userSkillsPath: '~/.agents/skills',
    workspaceSkillsRelativePath: '.agents/skills',
    origin: 'builtin',
    kind: 'desktop',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    extraUserSkillsPaths: ['~/.codex/skills'],
    extraWorkspaceSkillsRelativePaths: ['.codex/skills'],
    // The desktop app now ships as ChatGPT.app but keeps the Codex bundle
    // identifier; the classic ChatGPT app (com.openai.chat) is not Codex.
    appPaths: ['/Applications/ChatGPT.app', '/Applications/Codex.app', '~/Applications/ChatGPT.app', '~/Applications/Codex.app'],
    appBundleIds: ['com.openai.codex'],
    documentationUrl: 'https://developers.openai.com/codex/skills',
  },
  {
    id: 'gemini-cli',
    name: 'Gemini CLI',
    icon: 'G',
    userSkillsPath: '~/.gemini/skills',
    workspaceSkillsRelativePath: '.gemini/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    command: 'gemini',
    versionArgs: ['--version'],
    documentationUrl: 'https://geminicli.com/docs/cli/using-agent-skills/',
  },
  {
    id: 'kimi-code',
    name: 'Kimi Code CLI',
    icon: 'K',
    userSkillsPath: '~/.kimi-code/skills',
    workspaceSkillsRelativePath: '.kimi-code/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    command: 'kimi',
    versionArgs: ['--version'],
    documentationUrl: 'https://www.kimi.com/code/docs/en/kimi-code-cli/customization/skills.html',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    icon: 'Cu',
    userSkillsPath: '~/.cursor/skills',
    workspaceSkillsRelativePath: '.cursor/skills',
    origin: 'builtin',
    kind: 'desktop',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    // Cursor also supports Claude and Codex compatibility roots.
    extraUserSkillsPaths: ['~/.claude/skills', '~/.codex/skills'],
    extraWorkspaceSkillsRelativePaths: ['.claude/skills', '.codex/skills'],
    appPaths: ['/Applications/Cursor.app'],
    documentationUrl: 'https://prod.cursor.com/help/customization/skills',
  },
  {
    id: 'cursor-cli',
    name: 'Cursor CLI',
    icon: 'Cu',
    userSkillsPath: '~/.cursor/skills',
    workspaceSkillsRelativePath: '.cursor/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    extraUserSkillsPaths: ['~/.claude/skills', '~/.codex/skills'],
    extraWorkspaceSkillsRelativePaths: ['.claude/skills', '.codex/skills'],
    command: 'cursor-agent',
    versionArgs: ['--version'],
    executablePaths: ['~/.local/bin/cursor-agent'],
    documentationUrl: 'https://docs.cursor.com/en/cli/installation',
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    icon: 'O',
    userSkillsPath: '~/.config/opencode/skills',
    workspaceSkillsRelativePath: '.opencode/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    extraUserSkillsPaths: ['~/.claude/skills'],
    extraWorkspaceSkillsRelativePaths: ['.claude/skills'],
    command: 'opencode',
    versionArgs: ['--version'],
    documentationUrl: 'https://opencode.ai/docs/skills/',
  },
  {
    id: 'github-copilot-cli',
    name: 'GitHub Copilot CLI',
    icon: 'GH',
    userSkillsPath: '~/.copilot/skills',
    workspaceSkillsRelativePath: '.github/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    extraUserSkillsPaths: ['~/.claude/skills'],
    extraWorkspaceSkillsRelativePaths: ['.claude/skills'],
    command: 'copilot',
    versionArgs: ['--version'],
    documentationUrl: 'https://docs.github.com/en/copilot/how-tos/copilot-cli/customize-copilot/add-skills',
  },
  {
    id: 'vscode-copilot',
    name: 'GitHub Copilot for VS Code',
    icon: 'VS',
    userSkillsPath: '~/.copilot/skills',
    workspaceSkillsRelativePath: '.github/skills',
    origin: 'builtin',
    kind: 'desktop',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    extraUserSkillsPaths: ['~/.claude/skills'],
    extraWorkspaceSkillsRelativePaths: ['.claude/skills'],
    extensionIds: ['GitHub.copilot-chat'],
    extensionRoots: ['~/.vscode/extensions', '~/.vscode-insiders/extensions'],
    documentationUrl: 'https://code.visualstudio.com/docs/agent-customization/agent-skills',
  },
  {
    id: 'cline',
    name: 'Cline',
    icon: 'Cl',
    userSkillsPath: '~/.cline/skills',
    workspaceSkillsRelativePath: '.cline/skills',
    origin: 'builtin',
    kind: 'desktop',
    readsUserAgents: false,
    readsWorkspaceAgents: false,
    extraWorkspaceSkillsRelativePaths: ['.clinerules/skills', '.claude/skills'],
    extensionIds: ['saoudrizwan.claude-dev'],
    extensionRoots: ['~/.vscode/extensions', '~/.vscode-insiders/extensions'],
    documentationUrl: 'https://docs.cline.bot/customization/skills',
  },
  {
    id: 'roo-code',
    name: 'Roo Code',
    icon: 'R',
    userSkillsPath: '~/.roo/skills',
    workspaceSkillsRelativePath: '.roo/skills',
    origin: 'builtin',
    kind: 'desktop',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    extensionIds: ['RooVeterinaryInc.roo-cline'],
    extensionRoots: ['~/.vscode/extensions', '~/.vscode-insiders/extensions'],
    documentationUrl: 'https://roocodeinc.github.io/Roo-Code/features/skills/',
  },
  {
    id: 'windsurf',
    name: 'Devin Desktop / Windsurf Cascade',
    icon: 'W',
    userSkillsPath: '~/.codeium/windsurf/skills',
    workspaceSkillsRelativePath: '.devin/skills',
    origin: 'builtin',
    kind: 'desktop',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    // The current docs are published under Devin Desktop. They explicitly keep
    // reading the former Windsurf roots for existing Cascade installs.
    extraUserSkillsPaths: ['~/.config/devin/skills', '~/.claude/skills'],
    extraWorkspaceSkillsRelativePaths: ['.windsurf/skills', '.claude/skills'],
    // Candidate locations based on current and previous product names; the
    // detector still checks for a valid app bundle before reporting installed.
    appPaths: ['/Applications/Devin.app', '/Applications/Windsurf.app', '~/Applications/Devin.app', '~/Applications/Windsurf.app'],
    documentationUrl: 'https://docs.devin.ai/desktop/cascade/skills',
  },
  {
    id: 'amp',
    name: 'Amp',
    icon: 'A',
    // `amp skill add --global` installs into `~/.config/agents/skills`.
    userSkillsPath: '~/.config/agents/skills',
    workspaceSkillsRelativePath: '.agents/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    extraUserSkillsPaths: ['~/.config/amp/skills', '~/.claude/skills'],
    extraWorkspaceSkillsRelativePaths: ['.claude/skills'],
    command: 'amp',
    versionArgs: ['version'],
    documentationUrl: 'https://ampcode.com/docs/customize/skills',
  },
  {
    id: 'goose',
    name: 'Goose',
    icon: 'Go',
    userSkillsPath: '~/.agents/skills',
    workspaceSkillsRelativePath: '.agents/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    // Goose's own roots are documented under backward compatibility; its writer uses the shared roots.
    extraUserSkillsPaths: ['~/.config/goose/skills', '~/.claude/skills', '~/.config/agents/skills'],
    extraWorkspaceSkillsRelativePaths: ['.goose/skills', '.claude/skills'],
    command: 'goose',
    versionArgs: ['--version'],
    documentationUrl: 'https://goose-docs.ai/docs/guides/context-engineering/using-skills/',
  },
  {
    id: 'pi',
    name: 'Pi',
    icon: 'π',
    userSkillsPath: '~/.pi/agent/skills',
    workspaceSkillsRelativePath: '.pi/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    command: 'pi',
    versionArgs: ['--version'],
    documentationUrl: 'https://pi.dev/docs/latest/skills',
  },
  {
    id: 'grok-build',
    name: 'Grok Build',
    icon: 'X',
    userSkillsPath: '~/.grok/skills',
    workspaceSkillsRelativePath: '.grok/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: true,
    readsWorkspaceAgents: true,
    // xAI documents Claude and Cursor-compatible skill roots as enabled by
    // default. `.agents/skills` is also natively scanned by Grok Build.
    extraUserSkillsPaths: ['~/.claude/skills', '~/.cursor/skills'],
    extraWorkspaceSkillsRelativePaths: ['.claude/skills', '.cursor/skills'],
    command: 'grok',
    versionArgs: ['--version'],
    documentationUrl: 'https://github.com/xai-org/grok-build/blob/main/crates/codegen/xai-grok-pager/docs/user-guide/08-skills.md',
  },
  {
    id: 'antigravity',
    name: 'Google Antigravity',
    icon: 'Ag',
    userSkillsPath: '~/.gemini/config/skills',
    workspaceSkillsRelativePath: '.agents/skills',
    origin: 'builtin',
    kind: 'desktop',
    readsUserAgents: false,
    readsWorkspaceAgents: true,
    extraUserSkillsPaths: ['~/.gemini/antigravity/skills'],
    extraWorkspaceSkillsRelativePaths: ['.agent/skills'],
    // Conventional macOS install candidates; the detector validates the bundle
    // structure and executable before marking this application as installed.
    appPaths: ['/Applications/Antigravity.app', '~/Applications/Antigravity.app'],
    documentationUrl: 'https://antigravity.google/docs/skills',
  },
  {
    id: 'antigravity-cli',
    name: 'Antigravity CLI',
    icon: 'A>',
    userSkillsPath: '~/.gemini/antigravity-cli/skills',
    workspaceSkillsRelativePath: '.agents/skills',
    origin: 'builtin',
    kind: 'cli',
    readsUserAgents: false,
    readsWorkspaceAgents: true,
    command: 'agy',
    versionArgs: ['--version'],
    executablePaths: ['~/.local/bin/agy'],
    documentationUrl: 'https://antigravity.google/docs/skills',
  },
];
